### ISSUE TITLE
No map and info

### ISSUE THREAD

**Issue by crimzby** [devpoole2907/helldivers-companion-support#1]
When i run the app, there is no information and map on the screen 
![IMG_6780](https://github.com/devpoole2907/helldivers-companion-support/assets/165159209/816ce9fa-afba-4b0f-9388-ef0267149f97)

**Comment by devpoole2907** [comment]
The api is currently getting heavily rate limited due to all the divers downloading the app! I apologise I'm working on a solution - wasn't expecting this many people!!

**Comment by devpoole2907** [comment]
This issue should be resolved now, cheers
