### ISSUE TITLE
Display issues for iPhone 13 mini

### ISSUE THREAD

**Issue by ptfeltey** [devpoole2907/helldivers-companion-support#3]
![image](https://github.com/devpoole2907/helldivers-companion-support/assets/56047149/18b234c8-b266-4a26-aae4-482da436689f)

While on the 13 mini I noticed that there is some aspect display issues for everything on screen

**Comment by devpoole2907** [comment]
Thanks for the heads up :) I'll look into this and release a fix asap!

**Comment by devpoole2907** [comment]
I figured out the cause of the issue - in iOS accessibility settings if you have "Button Shapes" turned on it will force the tab bar to be wider, pushing all the content off screen. You can turn this off, or I can find a way to make it ignore that setting ![image](https://github.com/devpoole2907/helldivers-companion-support/assets/131243847/81910f60-926b-48e9-ab5a-2efe5ecd4584)

**Comment by ptfeltey** [comment]
Awesome thanks for the heads up!!
