### ISSUE TITLE
Title too long on iPhone homescreen

### ISSUE THREAD

**Issue by dieugab** [devpoole2907/helldivers-companion-support#4]
This is by far the most detailed companion app, however the app name on the homescreen is too long and thus gets truncated. Should ideally be just called "War Monitor" ![image](https://github.com/devpoole2907/helldivers-companion-support/assets/61377476/1d492054-c742-4b80-ab41-dda5abf0e434)

**Comment by devpoole2907** [comment]
Hey - I've kept it long like that for the sake of it showing up when you search "Helldivers 2" in the search bar/spotlight in iOS

**Comment by dieugab** [comment]
Hi @devpoole2907 thanks for taking the time to reply. 

If it showing up in search is important, why not flat out rename it to "Helldivers II"? It currently sticks out like a sore thumb compared to other apps

**Comment by devpoole2907** [comment]
Latest update just released has set it to just be War Monitor :)
