### ISSUE TITLE
Bullets Fired / Bullets hit Swapped

### ISSUE THREAD

**Issue by Icebr3aker1** [devpoole2907/helldivers-companion-support#5]
![IMG_6798](https://github.com/devpoole2907/helldivers-companion-support/assets/166715388/0d46745c-5e4f-45b8-a85b-4377552f39b0)
Hi,

it seems that there’s a mix up between bullets fired and bullets hit, the accuracy is at 100%.

With kind regards

**Comment by devpoole2907** [comment]
Good spot! However this is actually the data returned from the api, not a bug. So it would seem it counts bullets travelling through enemies etc!
