### ISSUE TITLE
Problem with widgets

### ISSUE THREAD

**Issue by ChaoticTemplar** [devpoole2907/helldivers-companion-support#6]
Hey im trying to use the widgets feature for the war monitor but it wont let me, i am currently using a iphone SE if that helps

**Comment by devpoole2907** [comment]
Hey what do you mean but it won't let you? Are they not showing up in the list of widgets?

**Comment by ChaoticTemplar** [comment]
> Hey what do you mean but it won't let you? Are they not showing up in the list of widgets?

Yes, i go to my „add widgets“ button when im in the home screen editor and i dont have any options for your app

**Comment by devpoole2907** [comment]
Strange, what version of iOS are you on? I've had this issue occur before, had to delete, restart the phone then reinstall the app

**Comment by ChaoticTemplar** [comment]
Im on 16.2

**Comment by devpoole2907** [comment]
Ah update to 16.4 or greater if you can, I think the widgets might require that version at least - I'll double check when I can later though, then release an update to lower it to 16.0 if it is restricted to 16.4 :)

**Comment by ChaoticTemplar** [comment]
Alright, thank you for your time

**Comment by devpoole2907** [comment]
Yep! It was limited to 16.4 minimum, forgot to lower it after I lowered the app requirements even further to iOS 16.0 the other day. Next update will bring this down to 16.0 :)
